[package]
name = "local-event"
version = "0.1.3"
edition = "2024"
authors = ["George Miao <gm@miao.dev>"]
license = "MIT"
description = "Single-threaded version of `event_listener`"
repository = "https://github.com/George-Miao/local-event"

[dev-dependencies]
compio = { version = "0.19", features = ["time"] }
event-listener = "5.4"
pollster = { version = "0.4.0", features = ["macro"] }
